version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3001:3000"
    networks:
      - app_network
      - db_network
    container_name: chilowallet
    restart: "no"
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}

networks:
  app_network:
    driver: bridge
    external: true
  db_network:
    driver: bridge
    external: true
