version: "3.9"

services:
  db:
    image: postgres:13
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

networks:
  app_network:
    driver: bridge
