version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.production
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      # NginxからホストOS側でデプロイしているSPサーバーを見にいく
      - hostos:172.18.0.1
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/workspace/static
      - ${SSL_CERTS_DIR}/signed.crt:/etc/nginx/conf.d/signed.crt
      - ${SSL_CERTS_DIR}/domain.key:/etc/nginx/conf.d/domain.key
      - ${SSL_CERTS_DIR}/signed_ep.crt:/etc/nginx/conf.d/signed_ep.crt
      - ${SSL_CERTS_DIR}/domain_ep.key:/etc/nginx/conf.d/domain_ep.key
      - ./50x.html:/usr/share/nginx/html/50x.html
    restart: always
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3001:3000"
    networks:
      - app_network
      - db_network
    container_name: chilowallet
    restart: "no"
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "7"

networks:
  app_network:
    driver: bridge
    external: true
  db_network:
    driver: bridge
    external: true
