version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    volumes:
      - ${SSL_CERTS_DIR}:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    environment:
      # FORCE_RENEW: 'true'
      STAGE: production
      DOMAINS: "${ALLOWED_HOSTS} -> http://web:8080/"
    depends_on:
      - web

  web:
    image: nginx:1.23.1
    expose:
      - 8080
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/workspace/static
      - ./50x.html:/usr/share/nginx/html/50x.html
    restart: always

  db:
    image: postgres:13
    hostname: db
    env_file:
      - ./.env
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

  deps:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
      target: deps
    image: deps:latest
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
      target: builder
    image: bundler:latest
  chilowallet:
    image: chilowallet
    ports:
      - "3000:3000"
    networks:
      - app_network
    container_name: chilowallet
    restart: "no"

networks:
  app_network:
    driver: bridge
    external: true
