version: "3.9"

services:
  #   app:
  #     build:
  #       context: .
  #     volumes:
  #       - .:/usr/src/app
  #     ports:
  #       - "3000:3000"
  #     command: npm run dev
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
