openapi: 3.0.3

info:
  title: OpenBadgeVC Walglet Server API
  description: OpenBadgeVCウォレットサーバAPI
  version: 0.1.0

servers:
  - url: https://openbadgevcwallet.example.com/api/v1

tags:
  - name: user_badgelist
    description: バッジリスト取得
  - name: entry
    description: ウォレット作成
  - name: credential list
    description: VC一覧
  - name: credential delete
    description: VC削除
  - name: badge list
    description: バッジデータ取得
  - name: badge convert
    description: バッジをVCに変換しDBに保存
  - name: badge metadata
    description: バッジのmetadataを取得
  - name: submission sendmail
    description: 確認コードを入力されたemailアドレスに送信
  - name: submission vc
    description: バッジデータの提出

paths:
  /user_badgelist:
    post:
      tags:
        - user_badgelist
      description: 対象ユーザのの保持バッジリストを返す
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user_badgelist"
        "400":
          description: Bad request
        "500":
          description: Internal Server Error
  /entry:
    post:
      tags:
        - entry
      description: ログイン情報をもとにウォレットを登録します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "400":
          description: Bad request
        "401":
          description: Un Authrized Error
        "500":
          description: Internal Server Error
  /credential/list:
    get:
      tags:
        - credential list
      description: ログインユーザーが保有するバッジのリストを返却します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
        - name: badgeName
          in: query
          description: serch form in badge name
          schema:
            type: string
        - name: issuedFrom
          in: query
          description: serch form in issued from
          schema:
            type: string
        - name: issuedTo
          in: query
          description: serch form in issued to
          schema:
            type: string
        - name: sortState
          in: query
          description: serch form in sort state
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/vcList"
        "400":
          description: Bad request
        "401":
          description: Un Authrized Error
        "500":
          description: Internal Server Error
  /credential/delete/{id}:
    post:
      tags:
        - credential delete
      description: 選択したVCをDBから削除します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE6
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: delete from badge vc id
          required: true
          schema:
            type: number
      responses:
        "204":
          description: Successful operation
        "400":
          description: Bad request
        "401":
          description: Un Authrized Error
        "500":
          description: Internal Server Error
  /badge/list:
    post:
      tags:
        - badge list
      description: 選択された発行者のMoodleにあるバッジのリストを取得します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                lmsId:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badgeList"
        "400":
          description: Bad request
        "500":
          description: Internal Server Error
  /badge/convert:
    post:
      tags:
        - badge convert
      description: 選択したバッジをVCに変換し、DBに保存します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE6
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uniqueHash:
                  type: string
                email:
                  type: string
                badgeMetaData:
                  type: string
                lmsId:
                  type: string
                lmsName:
                  type: string
      responses:
        "200":
          description: Successful operation
        "400":
          description: Bad request
        "500":
          description: server error
  /badge/metadata:
    get:
      tags:
        - badge metadata
      description: 一覧で選択されたバッジのメタデータを返却します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
        - name: uniquehash
          in: query
          description: select badge uniquehash
          required: true
          schema:
            type: string
        - name: lmsUrl
          in: query
          description: select lms url
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badgeMetaData"
        "400":
          description: Bad request
        "500":
          description: Internal Server Error
  /submission/sendmail:
    post:
      tags:
        - submission sendmail
      description: 確認コードを入力されたemailアドレスに送信します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  hashConfirmCode:
                    type: string
        "400":
          description: Bad request
        "500":
          description: Internal Server Error
  /submission/vc:
    post:
      tags:
        - submission vc
      description: バッジを提出します
      parameters:
        - name: saml
          in: header
          description: SAML by BASE64
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                consumerId:
                  type: string
                email:
                  type: string
                badgeVcId:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        "400":
          description: Bad request
        "500":
          description: Internal Server Error

components:
  schemas:
    user_badgelist:
      type: object
      properties:
        badge_list:
          type: array
          items:
            type: object
            properties:
              badge_class:
                type: string
              badge_name:
                type: string
            additionalProperties: false
            required:
              - badge_class
              - badge_name
      additionalProperties: false
      required:
        - badge_list

    vcList:
      type: object
      properties:
        badgeVc:
          type: array
          items:
            properties:
              badgeVcId:
                type: integer
              badgeName:
                type: string
              badgeIssuerName:
                type: string
              badgeIssuedon:
                type: string
              vcDataPayload:
                type: string
              submissions:
                type: array
                items:
                  type: object
                  properties:
                    customerName:
                      type: string
                    submitedAt:
                      type: string
            required:
              - badgeVcId
              - walletId
              - badgeName
        submissionsAll:
          $ref: "#/components/schemas/submissions"
        totalBadgeCount:
          type: number
      required:
        - badgeVc

    submissions:
      type: object
      properties:
        totalSubmission:
          type: integer
        detailSubmissions:
          type: array
          items:
            type: object
            properties:
              cabinetToSubmit:
                type: string
              submitCount:
                type: integer
            required:
              - cabinetToSubmit
              - submitCount

    badgeList:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
          name:
            type: string
          description:
            type: string
          timecreated:
            type: integer
          issuername:
            type: string
          issuerurl:
            type: string
          expireddate:
            type: integer
          message:
            type: string
          uniquehash:
            type: string
          dateissued:
            type: integer
          email:
            type: string
          badgeurl:
            type: string
          vcConverted?:
            type: boolean

    badgeMetaData:
      type: object
      properties:
        "@context":
          type: string
        id:
          type: string
        type:
          type: string
        recipient:
          $ref: "#/components/schemas/recipient"
        issuedOn:
          type: string
          format: date-time
        expires:
          type: string
          format: date-time
        badge:
          $ref: "#/components/schemas/badge"
        verify:
          $ref: "#/components/schemas/verify"

    badge:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        name:
          type: string
        description:
          type: string
        image:
          type: string
        criteria:
          $ref: "#/components/schemas/criteria"
        issuer:
          $ref: "#/components/schemas/issuer"

    criteria:
      type: object
      properties:
        narrative:
          type: string

    issuer:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        name:
          type: string
        url:
          type: string
        email:
          type: string

    recipient:
      type: object
      properties:
        type:
          type: string
        identity:
          type: string

    verify:
      type: object
      properties:
        type:
          type: string
        url:
          type: string
