services:
  app:
    tty: true
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - ../node_modules:/app/node_modules
volumes:
  node_modules:
